from .. import Event

from .PT_LOG import PT_LOG
from .PT_ERROR import PT_ERROR
from .PT_WARNING import PT_WARNING
from .PT_SUCCESS import PT_SUCCESS
from .PT_SEND_GCODE import PT_SEND_GCODE
from .PT_RESUME_PRINT import PT_RESUME_PRINT
from .PT_PAUSE_PRINT import PT_PAUSE_PRINT
from .PT_SAVE_TEMP import PT_SAVE_TEMP
from .PT_LOAD_TEMP import PT_LOAD_TEMP

EVENTS_DICT: dict = {
    "PT_LOG": PT_LOG,
    "PT_ERROR": PT_ERROR,
    "PT_WARNING": PT_WARNING,
    "PT_SEND_GCODE": PT_SEND_GCODE,
    "PT_RESUME_PRINT": PT_RESUME_PRINT,
    "PT_PAUSE_PRINT": PT_PAUSE_PRINT,
    "PT_SAVE_TEMP": PT_SAVE_TEMP,
    "PT_LOAD_TEMP": PT_LOAD_TEMP,
}
